-- liquibase formatted sql
-- changeset ALT_MKT_0.1:ADD1CLASS1STAT1CD-1
USE DATABASE AIGI_EDR_COMMONMODEL;
USE SCHEMA COMMON;

ALTER TABLE RAW_CAD
ADD COLUMN CLASS_STAT_CD  VARCHAR(50); --Added as part of Alt MKT 0.1 release
